server:
  port: 8081

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yeecode?serverTimezone=UTC
    username: root
    password: 123
    # ignore this line in highly mysql-connector version: 8.0.17
    driver-class-name: com.mysql.jdbc.Driver